# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://mikemylonakis.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Michail Mylonakis"
title: "{ Mike Mylonakis }"
description: "Blog and website of Mike Mylonakis, blogging mainly for tech. Opinions expressed are mine."
keywords: "mike, mylonakis, sestus, michail mylonakis"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/icons8-businessman-24.png"

#background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 8
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Stop overthinking... Start doing!"

me-img: "/img/me.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/me-36p.png"
icon-48p: "/img/web-app/me-48p.png"
icon-72p: "/img/web-app/me-72p.png"
icon-96p: "/img/web-app/me-96p.png"
icon-144p: "/img/web-app/me-144p.png"
icon-192p: "/img/web-app/me-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "mikemylonakis"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ubs.png"
    date: "July 2017 - Present"
    description: "Front Office Data Scientist - Quantitative Developer at UBS, London, building the next generation Data Science Platform for the eFX trading desk"
  - image: "/img/timeline/commission.png"
    date: "March 13-15 2017"
    description: "Selected amongst several teams to represent Greece in the <a href=\"https://ec.europa.eu/eurostat/cros/content/european-big-data-hackathon-0_en\">European Big Data Hackathon</a>. Ranked 9th out of 22 EU countries" 
  - image: "/img/timeline/atypon.png"
    date: "April 2016 - June 2017"
    description: "Software Engineer (Big Data) at Atypon, Athens, worked on the development and maintenance of <a href=\"https://www.atypon.com/products/literatum\">Literatum</a>"
  - image: "/img/timeline/kapodistrian.png"
    date: "November 2015 - December 2017"
    description: "Master of Science (MSc) - National and Kapodistrian University of Athens, Department of Informatics and Telecommunications - Computer Networking"
  - image: "/img/timeline/nokia.png"
    date: "April 2014 - March 2016"
    description: "Software Engineer at Nokia, Athens, worked at a POC on <a href=\"https://networks.nokia.com/solutions/flexible-service-chaining\"> Flexible Service Chaining</a>, and on the development - maintenance of <a href=\"https://networks.nokia.com/products/flexi-network-gateway\">Flexi NG</a>"
  - image: "/img/timeline/ntua.png"
    date: "October 2006 - May 2013"
    description: "Master of Engineering (MEng) - National Technical University of Athens - Electrical and Computer Engineering"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "mike@mikemylonakis.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Welcome :smiley: I'm Mike Mylonakis and I am currently working as a Data Scientist - Quantitative Developer at UBS, London. My areas of interest include Linux, Data Science (particularily interested in Data Engineering) and Software Architecture. During my spare time I enjoy playing with my Raspberry PIs and learning new stuff."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/sestus"
  - title: "stack-overflow"
    url: "https://stackoverflow.com/users/2254704/sestus"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/mmilonakis"
  - title: "facebook"
    url: "https://www.facebook.com/michail.milonakis"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: sestus
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji

pgp: "https://gist.githubusercontent.com/sestus/7fad2cd01c1b7da7e6ff06dcc240ef3e/raw/ee5988c947c4004aac9889f765133f15e1870266/995FF86A.asc"
